lambdas:

  snowplowconsumer:
    code: snowplowconsumer
    handler: code.handler
    runtime: python
    timeout: 20
    policies:

      read_kinesis:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "kinesis:DescribeStream"
              - "kinesis:ListStreams"
              - "kinesis:GetShardIterator"
              - "kinesis:GetRecords"
            Resource: "*"
            Effect: "Allow"

      write_dynamo:
            Version: "2012-10-17"
            Statement:
                -
                    Action:
                        - "dynamodb:DescribeTablem"
                        - "dynamodb:GetItem"
                        - "dynamodb:Query"
                        - "dynamodb:Scan"
                        - "dynamodb:UpdateItem"
                    Resource: "*"
                    Effect: "Allow"
