---
project: contexts
default-region: eu-west-1
code-bucket: gordon-contexts-0do1mc7
pip-extra: --cache-dir=/tmp/
apps:
  - gordon.contrib.lambdas
  - helloworld

contexts:
    default:
        username: ref://Username
        password: ref://Password
        bucket: ref://ImagesBucket
