lambdas:

  version:
    code: version
    handler: version.handler
    runtime: python2.7
    description: Publishes new versions of Lambdas.
    timeout: 300
    cli-output: False
    policies:
      manage_version:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "lambda:PublishVersion"
              - "lambda:GetFunction"
            Resource: "arn:aws:lambda:*:*:*"
            Effect: "Allow"
