---
project: cron10
default-region: eu-west-1
code-bucket: gordon-cron10-0do1mc8
apps:
  - gordon.contrib.lambdas
  - helloworld

events:
  every_night:
    schedule_expression: cron(0 0 * * ? *)
    targets:
        say_hello:
            lambda: helloworld.hellopy

  update_dns:
    schedule_expression: rate(3 minutes)
    event_pattern:
        source:
            - aws.ec2
        detail:
            state:
                - pending
    targets:
        say_hello:
            lambda: helloworld.hellopy
