---
project: kinesisexample
default-region: eu-west-1
code-bucket: gordon-kinesispython-0do1mc7
apps:
  - gordon.contrib.helpers
  - gordon.contrib.lambdas
  - exampleapp

kinesis:
  example_kinesis_integration:
    lambda: exampleapp.kinesisconsumer
    stream: ref://KinesisIntegrationArn
    batch_size: 1
    starting_position: LATEST
