---
project: telegramexample
default-region: eu-west-1
code-bucket: gordon-telegramexample-0do1mc7
apps:
  - gordon.contrib.lambdas
  - botapp

contexts:
  default:
    token: ref://Token

apigateway:
  telegramexampleapi:
    description: My telegram API
    resources:
      /my-js-bot-webhook:
        methods: POST
        integration:
          lambda: botapp.javascript_bot
